### ISSUE TITLE
test

### ISSUE THREAD

**Issue by datnguyenE18** [datnguyenE18/IT_General#1]
Triển khai helm chart controller cho VKE, đóng gói các plugin của K8s Cluster thành helm char: CNI, CSI, Velero, CCM….

- [x] **Cluster API:** Kiến trúc, mô hình mạng, các loại controller: core, boostrap, control-plane, infrastructure và chức năng của từng cái, sơ đồ tương tác giữa các thành phần, future work
    - [x] Quick start Cluster API theo [docs](https://cluster-api.sigs.k8s.io/user/quick-start.html)
    - [x] Khi làm tới bước [Apply the workload cluster](https://cluster-api.sigs.k8s.io/user/quick-start.html#apply-the-workload-cluster):
    - [x] 1. Phân tích các loại objects trong manifest đó
    - [x] 2. Spec trong objects đó có ý nghĩa gì
    - [x] 3. Xem logs từng thành phần controller và phân tích ý nghĩa (Mỗi controller chịu trách nhiệm reconcile objects nào, các objects đó biến đổi ra sao trong quá trình khởi tạo cụm )
- [x] **Cài đặt FluxCD**
- [ ] **Đóng gói các plugin của K8s Cluster thành helm chart.** Tham khảo:
  - https://github.com/vmware-tanzu/helm-charts/tree/main/charts
  - https://github.com/kubernetes/cloud-provider-openstack/tree/master/charts
- [ ] **Chỉnh sửa CMP**

**Comment by datnguyenE18** [comment]
Triển khai helm chart controller cho VKE, đóng gói các plugin của K8s Cluster thành helm char: CNI, CSI, Velero, CCM….

- [x] **Cluster API:** Kiến trúc, mô hình mạng, các loại controller: core, boostrap, control-plane, infrastructure và chức năng của từng cái, sơ đồ tương tác giữa các thành phần, future work
    - [x] Quick start Cluster API theo [docs](https://cluster-api.sigs.k8s.io/user/quick-start.html)
    - [x] Khi làm tới bước [Apply the workload cluster](https://cluster-api.sigs.k8s.io/user/quick-start.html#apply-the-workload-cluster):
    - [x] 1. Phân tích các loại objects trong manifest đó
    - [x] 2. Spec trong objects đó có ý nghĩa gì
    - [x] 3. Xem logs từng thành phần controller và phân tích ý nghĩa (Mỗi controller chịu trách nhiệm reconcile objects nào, các objects đó biến đổi ra sao trong quá trình khởi tạo cụm )
- [x] **Cài đặt FluxCD**
- [ ] **Đóng gói các plugin của K8s Cluster thành helm chart.** Tham khảo:
  - https://github.com/vmware-tanzu/helm-charts/tree/main/charts
  - https://github.com/kubernetes/cloud-provider-openstack/tree/master/charts
- [ ] **Chỉnh sửa CMP**

**Comment by datnguyenE18** [comment]
# Assigment: 
Triển khai helm chart controller cho VKE, đóng gói các plugin của K8s Cluster thành helm char: CNI, CSI, Velero, CCM….

## Phase 1:
- [x] **Nghiên cứu K8S nền tảng**
- [x] **Custom Controller**
- [x] **CRD - Custom Resource Definition**
- [ ] **Đọc về kubebuilder** (https://book.kubebuilder.io/ : 1.1 - 1.9)
- [x] **Quick start Cluster API**
- [ ] **Cài đặt FluxCD**
- [ ] **Đóng gói các plugin của K8s Cluster thành helm chart.** Tham khảo:
  - https://github.com/vmware-tanzu/helm-charts/tree/main/charts
  - https://github.com/kubernetes/cloud-provider-openstack/tree/master/charts
- [ ] **Chỉnh sửa CMP**

## Phase 2:
- [x] **Cluster API:** Kiến trúc, mô hình mạng, các loại controller: core, boostrap, control-plane, infrastructure và chức năng của từng cái, sơ đồ tương tác giữa các thành phần, future work
    - [x] Quick start Cluster API theo [docs](https://cluster-api.sigs.k8s.io/user/quick-start.html)
    - [x] Khi làm tới bước [Apply the workload cluster](https://cluster-api.sigs.k8s.io/user/quick-start.html#apply-the-workload-cluster):
    - [x] 1. Phân tích các loại objects trong manifest đó
    - [x] 2. Spec trong objects đó có ý nghĩa gì
    - [x] 3. Xem logs từng thành phần controller và phân tích ý nghĩa (Mỗi controller chịu trách nhiệm reconcile objects nào, các objects đó biến đổi ra sao trong quá trình khởi tạo cụm )
- [x] **Đọc về kubebuilder** (https://book.kubebuilder.io/ : 1.1 - 1.9)
- [x] **Cài đặt FluxCD**
- [ ] **Đóng gói các plugin của K8s Cluster thành helm chart.** Tham khảo:
- [ ] **Chỉnh sửa CMP**

## Phase 3:
Task: Tạo helm chart trên Manager Cluster rồi sync lên Workload Cluster
- [x] **Flux**
    - [x] Get started Flux
    - [x] Helm chart Flux
    - [x] Đóng gói các plugin của K8s Cluster thành helm chart.**
- [x] **Truy cập cụm test-cluster-p & vke-phase-2 để test**
- [ ] Hoàn thiện [http://git.viettel.vn:8180/cloud-native-cicd/kubernetes-engine/vke-python-sdk/-/merge_requests/67/diffs](url)

**Note**: 
* Các Phase là các giai đoạn sau 1 lần báo cáo
*  Mỗi task trong phase là các yêu cầu dự định trong một phase. Những task có tick là những task đã hoàn thành trong phase đó
* Các task chưa hoàn thành sẽ được chuyển sang phase sau hoặc hoãn.
